CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(255),

    email VARCHAR(320),

    password_hash VARCHAR(255),

    platform_role VARCHAR(50) NOT NULL,

    account_status VARCHAR(50) NOT NULL,

    anonymized_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT chk_users_platform_role
        CHECK (
            platform_role IN (
                'STUDENT',
                'ALUMNI',
                'SYSTEM_ADMIN'
            )
        ),

    CONSTRAINT chk_users_account_status
        CHECK (
            account_status IN (
                'PENDING_VERIFICATION',
                'ACTIVE',
                'SUSPENDED'
            )
        )
);
