CREATE TABLE email_verification_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    revoked_at TIMESTAMP,
    CONSTRAINT chk_verification_expiry CHECK (expires_at > created_at)
);
CREATE INDEX ix_verification_tokens_user ON email_verification_tokens(user_id);
