CREATE TABLE password_reset_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    revoked_at TIMESTAMP,
    CONSTRAINT password_reset_expiry_valid CHECK (expires_at > created_at)
);
CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens(user_id);
