CREATE TABLE departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL,
    department_code VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE programmes (
    programme_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(department_id),
    programme_name VARCHAR(150) NOT NULL,
    programme_code VARCHAR(30) NOT NULL UNIQUE
);
CREATE INDEX idx_programmes_department ON programmes(department_id);
CREATE TABLE programme_degrees (
    programme_degree_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id BIGINT NOT NULL REFERENCES programmes(programme_id),
    degree_level VARCHAR(20) NOT NULL CHECK (degree_level IN ('DIPLOMA', 'BACHELOR', 'MASTER', 'DOCTORATE')),
    duration_years INTEGER NOT NULL CHECK (duration_years BETWEEN 1 AND 20),
    minimum_year INTEGER NOT NULL CHECK (minimum_year BETWEEN 1 AND 20),
    maximum_year INTEGER NOT NULL CHECK (maximum_year BETWEEN 1 AND 20 AND maximum_year >= minimum_year),
    active BOOLEAN NOT NULL,
    UNIQUE (programme_id, degree_level)
);
CREATE TABLE skills (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE,
    category VARCHAR(100)
);
CREATE TABLE interests (
    interest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE
);
CREATE TABLE personal_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(user_id),
    profile_type VARCHAR(20) NOT NULL CHECK (profile_type IN ('STUDENT', 'ALUMNI')),
    programme_degree_id BIGINT NOT NULL REFERENCES programme_degrees(programme_degree_id),
    bio VARCHAR(2000),
    profile_photo_url VARCHAR(2048),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    student_number VARCHAR(40) UNIQUE,
    year_of_study INTEGER,
    expected_graduation_year INTEGER CHECK (expected_graduation_year BETWEEN 1900 AND 2200),
    project_availability BOOLEAN,
    mentorship_availability BOOLEAN,
    graduation_year INTEGER CHECK (graduation_year BETWEEN 1900 AND 2200),
    current_company VARCHAR(150),
    current_position VARCHAR(150),
    industry VARCHAR(100),
    career_background VARCHAR(2000),
    linkedin_url VARCHAR(2048),
    CONSTRAINT profile_role_fields CHECK (
        (profile_type = 'STUDENT' AND student_number IS NOT NULL AND year_of_study IS NOT NULL
            AND year_of_study BETWEEN 1 AND 20 AND project_availability IS NOT NULL AND mentorship_availability IS NOT NULL
            AND graduation_year IS NULL AND current_company IS NULL AND current_position IS NULL
            AND industry IS NULL AND career_background IS NULL AND linkedin_url IS NULL)
        OR
        (profile_type = 'ALUMNI' AND graduation_year IS NOT NULL AND student_number IS NULL AND year_of_study IS NULL
            AND expected_graduation_year IS NULL AND project_availability IS NULL AND mentorship_availability IS NULL)
    )
);
CREATE INDEX idx_profiles_degree ON personal_profiles(programme_degree_id);
CREATE TABLE profile_skills (
    profile_id BIGINT NOT NULL REFERENCES personal_profiles(profile_id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(skill_id),
    PRIMARY KEY (profile_id, skill_id)
);
CREATE TABLE profile_interests (
    profile_id BIGINT NOT NULL REFERENCES personal_profiles(profile_id) ON DELETE CASCADE,
    interest_id BIGINT NOT NULL REFERENCES interests(interest_id),
    PRIMARY KEY (profile_id, interest_id)
);
