ALTER TABLE personal_profiles ADD COLUMN details_visibility VARCHAR(30) NOT NULL DEFAULT 'CONNECTIONS_ONLY'
    CHECK (details_visibility IN ('ALL_MEMBERS', 'CONNECTIONS_ONLY'));

CREATE TABLE connections (
    connection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL REFERENCES users(user_id),
    receiver_id BIGINT NOT NULL REFERENCES users(user_id),
    user_low BIGINT NOT NULL REFERENCES users(user_id),
    user_high BIGINT NOT NULL REFERENCES users(user_id),
    open_low BIGINT,
    open_high BIGINT,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'REMOVED')),
    introductory_message VARCHAR(1000),
    requested_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,
    closed_at TIMESTAMP,
    CONSTRAINT connection_pair_order CHECK (user_low < user_high
        AND ((requester_id = user_low AND receiver_id = user_high) OR (requester_id = user_high AND receiver_id = user_low))),
    -- Nullable open keys make this constraint portable to PostgreSQL and H2.
    CONSTRAINT unique_open_connection UNIQUE (open_low, open_high),
    CONSTRAINT connection_open_state CHECK (
        (status IN ('PENDING', 'ACCEPTED') AND open_low IS NOT NULL AND open_high IS NOT NULL
            AND open_low = user_low AND open_high = user_high AND closed_at IS NULL)
        OR (status IN ('REJECTED', 'CANCELLED', 'REMOVED') AND open_low IS NULL AND open_high IS NULL AND closed_at IS NOT NULL)),
    CONSTRAINT connection_acceptance_state CHECK (
        (status IN ('ACCEPTED', 'REMOVED') AND accepted_at IS NOT NULL)
        OR (status IN ('PENDING', 'REJECTED', 'CANCELLED') AND accepted_at IS NULL))
);
CREATE INDEX idx_connections_requester_status ON connections(requester_id, status);
CREATE INDEX idx_connections_receiver_status ON connections(receiver_id, status);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES users(user_id),
    type VARCHAR(50) NOT NULL CHECK (type IN ('CONNECTION_REQUESTED', 'CONNECTION_ACCEPTED')),
    title VARCHAR(150) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    reference_type VARCHAR(50) NOT NULL CHECK (reference_type = 'CONNECTION'),
    reference_id BIGINT NOT NULL,
    event_key VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    dismissed_at TIMESTAMP,
    CONSTRAINT unique_recipient_event UNIQUE (recipient_id, event_key)
);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, notification_id);
