CREATE TABLE chat_conversations (
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low BIGINT NOT NULL REFERENCES users(user_id),
    user_high BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL,
    last_message_at TIMESTAMP NOT NULL,
    CHECK (user_low < user_high),
    UNIQUE (user_low,user_high)
);
CREATE INDEX idx_chat_low_activity ON chat_conversations(user_low,last_message_at);
CREATE INDEX idx_chat_high_activity ON chat_conversations(user_high,last_message_at);
CREATE TABLE chat_participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES chat_conversations(conversation_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    slot INTEGER NOT NULL CHECK (slot IN (1,2)),
    joined_at TIMESTAMP NOT NULL,
    UNIQUE (conversation_id,user_id),
    UNIQUE (conversation_id,slot)
);
CREATE TABLE chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES chat_conversations(conversation_id),
    sender_id BIGINT NOT NULL,
    client_message_id UUID NOT NULL,
    content VARCHAR(5000) NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    deleted_for_everyone_at TIMESTAMP,
    FOREIGN KEY (conversation_id,sender_id) REFERENCES chat_participants(conversation_id,user_id),
    UNIQUE (sender_id,client_message_id),
    UNIQUE (message_id,conversation_id)
);
CREATE INDEX idx_chat_messages_history ON chat_messages(conversation_id,message_id);
CREATE TABLE chat_message_states (
    state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    delivered_at TIMESTAMP,
    read_at TIMESTAMP,
    deleted_for_self_at TIMESTAMP,
    FOREIGN KEY (message_id,conversation_id) REFERENCES chat_messages(message_id,conversation_id),
    FOREIGN KEY (conversation_id,user_id) REFERENCES chat_participants(conversation_id,user_id),
    UNIQUE (message_id,user_id),
    CHECK (read_at IS NULL OR delivered_at IS NOT NULL)
);
CREATE INDEX idx_chat_states_unread ON chat_message_states(user_id,conversation_id,read_at);
